title = "UniWebViewTransform"
file = "UniWebViewTransform"

summary = """
Represents a transformation that can be applied to a UniWebView, including rotation and scaling.

The transformation includes:

- **Rotation**: The angle (in degrees) by which the web view should be rotated. Positive values rotate the web
view clockwise, while negative values rotate it counterclockwise.
- **Scaling**: The scale factors for the X and Y axes. A scale factor of 1.0 means no scaling, while values
greater than 1.0 enlarge the web view and values less than 1.0 shrink it.

This transformation is typically used in conjunction with the `SetTransform` method in `UniWebView` to apply visual
transformations to the web view.
"""

[[Properties]]
name = "Rotation"
returnType = "float"
hasSetter = true
summary = "The rotation of the web view in degrees."

[[Properties]]
name = "ScaleX"
returnType = "float"
hasSetter = true
summary = "The scaling factor applied to the X-axis of the web view."

[[Properties]]
name = "ScaleY"
returnType = "float"
hasSetter = true
summary = "The scaling factor applied to the Y-axis of the web view."
