title = "UniWebViewNativeResultPayload"
file = "uniwebviewnativeresultpayload"

[[Properties]]
name = "identifier"
returnType = "string"
hasSetter = false
summary = "The identifier bound to this payload. It would be used internally to identify the callback."

[[Properties]]
name = "resultCode"
returnType = "string"
hasSetter = false
summary = "The result code contained in this payload. Generally, \"0\" means the operation finished without problem, while a non-zero value means somethings goes wrong."

[[Properties]]
name = "data"
returnType = "string"
hasSetter = false
summary = "Return value or data from native. You should look at corresponding APIs to know what exactly contained in this."
