title = "UniWebViewTransitionEdge"
file = "uniwebviewtransitionedge"

[[Properties]]
name = "None"
returnType = "UniWebViewTransitionEdge"
hasSetter = false
summary = "No transition when showing or hiding."

[[Properties]]
name = "Top"
returnType = "UniWebViewTransitionEdge"
hasSetter = false
summary = "Transit the web view from/to top."

[[Properties]]
name = "Left"
returnType = "UniWebViewTransitionEdge"
hasSetter = false
summary = "Transit the web view from/to left."

[[Properties]]
name = "Bottom"
returnType = "UniWebViewTransitionEdge"
hasSetter = false
summary = "Transit the web view from/to bottom."

[[Properties]]
name = "Right"
returnType = "UniWebViewTransitionEdge"
hasSetter = false
summary = "Transit the web view from/to right."