title = "UniWebViewLogger"
file = "uniwebviewlogger"

[[Properties]]
name = "Instance"
returnType = "UniWebViewLogger"
hasSetter = false
summary = """
An instance of the UniWebView logger across the process. Normally you should use this for logging purpose
in UniWebView, instead of creating a new logger yourself.
"""
[[Properties.badges]]
name = "static"
color = "blue"

[[Properties]]
name = "LogLevel"
returnType = "UniWebViewLogger.Level"
hasSetter = true
summary = """
Current level of this logger. All messages above current level will be logged out.

The default level is `Critical`, which means the logger only prints errors and exceptions.
"""

[[Properties]]
name = "Level.Verbose"
returnType = "UniWebViewLogger.Level"
hasSetter = false
summary = "Lowest level. When set to `Verbose`, the logger will log out all messages."

[[Properties]]
name = "Level.Debug"
returnType = "UniWebViewLogger.Level"
hasSetter = false
summary = "Debug level. When set to `Debug`, the logger will log out most of messages up to this level."

[[Properties]]
name = "Level.Info"
returnType = "UniWebViewLogger.Level"
hasSetter = false
summary = "Info level. When set to `Info`, the logger will log out up to info messages."

[[Properties]]
name = "Level.Critical"
returnType = "UniWebViewLogger.Level"
hasSetter = false
summary = "Critical level. When set to `Critical`, the logger will only log out errors or exceptions."

[[Properties]]
name = "Level.Off"
returnType = "UniWebViewLogger.Level"
hasSetter = false
summary = "Off level. When set to `Off`, the logger will log out nothing."

[[Methods]]
name = "Verbose"
syntax = "Verbose(string message)"
returnType = "void"
summary = "Log a verbose message."
[[Methods.parameters]]
name = "message"
type = "string"
summary = "The message to log"

[[Methods]]
name = "Debug"
syntax = "Debug(string message)"
returnType = "void"
summary = "Log a debug message."
[[Methods.parameters]]
name = "message"
type = "string"
summary = "The message to log"

[[Methods]]
name = "Info"
syntax = "Info(string message)"
returnType = "void"
summary = "Log a info message."
[[Methods.parameters]]
name = "message"
type = "string"
summary = "The message to log"

[[Methods]]
name = "Critical"
syntax = "Critical(string message)"
returnType = "void"
summary = "Log a critical message."
[[Methods.parameters]]
name = "message"
type = "string"
summary = "The message to log"